import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,cpSync,writeFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {randomBytes} from 'node:crypto';
const root=resolve(import.meta.dirname,'..'),dir=mkdtempSync(join(tmpdir(),'deafnavi-research-import-'));
const backend=join(dir,'backend'),backup=join(dir,'backup'),data=join(dir,'data');mkdirSync(backup);cpSync(join(root,'server'),backend,{recursive:true});
const baseline=spawnSync('git',['show','34a7b1d:server/seed.json'],{cwd:root,encoding:'utf8'});assert.equal(baseline.status,0);writeFileSync(join(backend,'seed.json'),baseline.stdout);
const env={...process.env,DEAFNAVI_DATA_DIR:data,DEAFNAVI_LOCAL_TEST:'1'};
const hash=spawnSync('php',['test/directory-hash.php'],{cwd:root,input:randomBytes(24).toString('hex'),encoding:'utf8'}).stdout;
const run=(args,input)=>spawnSync('php',args,{cwd:root,env,input,encoding:'utf8'});
assert.equal(run([join(backend,'cli.php'),'init'],JSON.stringify({username:'testadmin',password_hash:hash})).status,0);
const getState=()=>run(['-r',`require '${join(root,'server/core.php').replaceAll('\\','/')}'; echo json(['users'=>query('SELECT * FROM users')->fetchAll(),'settings'=>query('SELECT * FROM settings')->fetchAll(),'submissions'=>query('SELECT * FROM submissions')->fetchAll(),'records'=>query('SELECT * FROM records ORDER BY id')->fetchAll()]);`]).stdout;
const before=JSON.parse(getState());
const result=run(['server/import-research.php','content/connect/import-20260905.json',backup]);assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/RESEARCH_IMPORT_OK/);
const after=JSON.parse(getState());for(const key of ['users','settings','submissions'])assert.deepEqual(after[key],before[key]);assert.equal(after.records.length,23);assert.equal(readdirSync(backup).length,1);
const again=run(['server/import-research.php','content/connect/import-20260905.json',backup]);assert.equal(again.status,1);assert.deepEqual(JSON.parse(getState()),after,'repeat/conflicting revisions cannot change any rows');
console.log(JSON.stringify({result:'RESEARCH_IMPORT_TESTS_OK',records:23,backupCount:1,repeatRejected:true,accountsSettingsSubmissionsUnchanged:true}));
