<?php
declare(strict_types=1);
function ui_icon(string $name): string {
    $paths=['map'=>'<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/>','pin'=>'<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>','edit'=>'<path d="m14 5 5 5M4 20l5-1L21 7l-5-5L4 14Z"/>','page'=>'<path d="M14 3H5v18h14V8Z M14 3v5h5M8 12h8M8 16h8"/>','expand'=>'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/>'];
    return '<svg class="dn-ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'.($paths[$name]??$paths['page']).'</svg>';
}
function action_link(string $href,string $label,string $icon='page'):string{return '<a class="dn-action-link" href="'.e($href).'">'.ui_icon($icon).'<span>'.e($label).'</span></a>';}
function map_page_2d(): string {
    $all=map_records();$mapped=count(array_filter($all,'map_located'));$prefs=[];
    foreach($all as $p)$prefs[$p['prefecture']]=$p['prefecture'];ksort($prefs);
    $body='<link rel="stylesheet" href="/cafe-map/leaflet/leaflet.css"><link rel="stylesheet" href="/cafe-map/leaflet/MarkerCluster.css"><link rel="stylesheet" href="/cafe-map/map-2d.css?v=1"><script type="module" src="/cafe-map/map-2d.js?v=1"></script><p class="dn-eyebrow">DEAF NAVI / CAFE MAP</p><p>地域から、行ってみたい手話カフェを探す。まとまった数字を選ぶと拡大し、店舗名からも地図を開けます。</p>'.action_link('/connect/sign-cafe/','営業時間を表で比較','page');
    $body.='<section id="atlas" class="dn-atlas"><div class="dn-atlas-controls" hidden><label>店舗・地域を検索<input type="search" id="atlas-search" placeholder="店舗名・東京都など" maxlength="100"></label><label>都道府県<select id="atlas-pref"><option value="">すべて</option>';
    foreach($prefs as $pref)$body.='<option>'.e($pref).'</option>';
    $body.='</select></label><button type="button" id="atlas-fit">'.ui_icon('map').'掲載地点全体</button><button type="button" id="atlas-fullscreen" hidden>'.ui_icon('expand').'大きく表示</button></div><div class="dn-atlas-layout"><div class="dn-atlas-map-wrap"><div id="atlas-map" aria-label="手話カフェ地図"></div><div id="atlas-cover"><div class="dn-map-emblem">'.ui_icon('map').'</div><h2>近くのカフェを、地図から。</h2><p>'.$mapped.'地点の住所付近を掲載しています。</p><button type="button" id="atlas-start" hidden>'.ui_icon('map').'地図を開く</button><p class="dn-muted">開くとOpenStreetMapへ表示範囲の地図画像をリクエストします。現在地は取得しません。</p><noscript><p>下の店舗名から詳細をご覧ください。</p></noscript></div><p id="atlas-state" role="status"></p></div><aside class="dn-atlas-sidebar"><div class="dn-atlas-list-heading"><h2>店舗から選ぶ</h2><p id="atlas-count">'.count($all).'件（地図掲載 '.$mapped.'件）</p><label class="dn-atlas-bounds" hidden><input id="atlas-bounds" type="checkbox" checked> 表示範囲の店舗に絞る</label></div><p id="atlas-empty" hidden>表示範囲に店舗がありません。「掲載地点全体」で戻せます。</p><ul class="dn-atlas-list">';
    foreach($all as $p){$located=map_located($p);$body.='<li data-atlas-item="'.e($p['slug']).'" data-prefecture="'.e($p['prefecture']).'"><p class="dn-atlas-area">'.e($p['prefecture'].' / '.$p['city']).'</p><h3><a href="'.e(record_path($p)).'">'.e($p['name']).'</a></h3><p>'.e(TYPES[$p['type']].' · '.STATUSES[$p['status']]).'</p><p class="dn-atlas-hours">'.e(($p['business_hours']??'')?:'営業時間未確認').'</p><div class="dn-atlas-actions">'.($located?'<button type="button" data-atlas-select="'.e($p['slug']).'" hidden>'.ui_icon('pin').'地図で見る</button>':'<span class="dn-muted">位置確認待ち</span>').action_link(record_path($p),'詳細').'</div></li>';}
    $body.='</ul></aside></div></section><p class="dn-muted">位置は住所付近の概略で、入口とは異なる場合があります。営業状況未確認の場所は事前に情報源をご確認ください。地図に載せられない場所も「表示範囲の店舗に絞る」を外すと一覧に残ります。</p><details><summary>地図の出典と利用について</summary><p>Leaflet 1.9.4（BSD-2-Clause）、Leaflet.markercluster 1.5.3（MIT）。背景地図：OpenStreetMap contributors。地図画像は操作中の表示範囲のみ取得し、一括保存は行いません。座標は住所検索結果を照合した概略位置です。</p><p><a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener noreferrer">背景地図の誤りを報告</a> / <a href="https://osmfoundation.org/wiki/Privacy_Policy" target="_blank" rel="noopener noreferrer">OpenStreetMapのプライバシーポリシー</a></p></details>'.action_link('/submit/?category=cafe','カフェ情報を提供','edit');
    return page('全国の手話カフェマップ',$body,'/connect/sign-cafe/map/','手話カフェを道路や駅のある2D地図から検索。店舗名・営業時間と地図を見比べ、拡大して探せます。');
}
